/* Generated by Together */

package org.yang.web.controller;

public class CreateBeanException extends Exception
{
   
   /**
 *    @roseuid 3B0AAF190011
   */
   public CreateBeanException()
   {
      super();	
   }

   /**
 *    @roseuid 3B0AAF190011
   */
   public CreateBeanException(String s)
   {
      super(s);	
   }
}
