/* Generated by Together */

package org.yang.services.domainMgr;

public class DomainFactory
{
    static public Domain createDomain(String classname)
    {
       try
       {
          return (Domain)Class.forName(classname).newInstance();
       }
       catch(Exception e)
       {
          e.printStackTrace();
          return null;
       }
    }
}