/* Generated by Together */

package org.yang.services.messageBus.FileSystem;
import org.yang.services.messageBus.Route;
import org.yang.services.messageBus.MessageTransmitter;
import org.yang.services.messageBus.InitException;
import org.yang.services.messageBus.MessageReceiver;
import org.yang.services.messageBus.MessageTrancieverFactory;

public class FSTrancieverFactoryImpl extends MessageTrancieverFactory
{
   private FSTrancieverFactoryImpl() {}

   public boolean createRoute(Route rt)
   {
      return false;
   }

   public boolean deleteRoute(Route rt)
   {
      return false;
   }

   public MessageTransmitter createTransmitter(Route rt) throws InitException
   {
      try
      {
         return new FileMessageTransmitterImpl(rt);
      }
      catch(Exception e)
      {
         throw new InitException(e.getMessage());
      }
   }

   public MessageReceiver createReceiver(String hostName, String id, Route rt, MessageReceiver receiver) throws InitException
   {
      return null;
   }
}