/* Generated by Together */

package org.yang.services.messageBus.JMS;

import javax.jms.MessageListener;
import org.yang.services.messageBus.Route;
import java.io.StringReader;
import javax.xml.parsers.SAXParserFactory;
import javax.xml.parsers.SAXParser;
import java.io.FileWriter;
import java.util.Date;
import javax.naming.NamingException;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import org.yang.services.messageBus.MessageReceiver;
import org.yang.services.messageBus.InitException;
import org.yang.services.messageBus.Message;
import org.yang.services.messageBus.MessageBus;
import javax.jms.TopicSubscriber;
import java.io.Serializable;
import org.apache.log4j.Category;
import org.yang.services.messageBus.DataReceivingException;

public class JMSTopicMessageReceiverImpl extends JMSTopicAdaptor implements  MessageListener, MessageReceiver
{
   static final long serialVersionUID = 3439536529228252188L;

   private int count = 0;

   private String site = null;
   public void setSite(String site) { this.site=site; }
   public String getSite() { return site; }

   private String channel = null;
   public void setChannel(String channel) { this.channel=channel; }
   public String getChannel() { return channel; }

   MessageReceiver realReceiver = null;
   public void setRealReceiver(MessageReceiver receiver) { this.realReceiver = realReceiver; }

   boolean isDurable = true;
   MessageReceiver receiver = null;
   TopicSubscriber subscriber = null;

   public JMSTopicMessageReceiverImpl(String id, Route rt, MessageReceiver receiver, boolean isDurable) throws NamingException, InitException
   {
      super(rt.getProperties());

      System.out.println("[JMSTopicMessageReceiverImpl::JMSTopicMessageReceiverImpl] ID: " + id + ", Route: " + rt.getName() + ", is Durable: " + isDurable);
      this.receiver = receiver;
      this.isDurable = isDurable;
      setId(id);
      initialize();
   }

   /************************************
    *  Implements method in JMSAdaptor *
    ************************************/

   public void resume() throws NamingException, InitException
   {
      initialize();
   }

   /*****************************************
    *  Implements method in JMSTopicAdaptor *
    *****************************************/

   public boolean isProvider()
   {
      return false;
   }

   /*****************************************
    *  Implements method in MessageReceiver *
    *****************************************/

   public void onMessage(Message msg)
   {
      receiver.onMessage(msg);
   }

   public Message getMessage(long timeout) throws DataReceivingException
   {
      try
      {
         log.debug("[getMessage] Check message from topic : my id = " + getId());
         if(null==subscriber)
            subscriber = prepareSubscriber(getId(), isDurable);

         Message msg = convertMessage(subscriber.receive(timeout));
         if(null!=msg)
            count++;
         return msg;
      }
      catch(Exception e)
      {
         log.error("Unable to receive message. ", e);
         subscriber = null;
         throw new DataReceivingException(e.getMessage());
      }
   }

   public Message getMessage() throws DataReceivingException
   {
      try
      {
         log.debug("[getMessage] Check message from topic : my id = " + getId());
         if(null==subscriber)
            subscriber = prepareSubscriber(getId(), isDurable);

         Message msg = convertMessage(subscriber.receive());
         if(null!=msg)
            count++;
         return msg;
      }
      catch(Exception e)
      {
         log.error("Unable to receive message. ", e);
         subscriber = null;
         throw new DataReceivingException(e.getMessage());
      }
   }

   /*****************************************
    *  Implements method in MessageListener *
    *****************************************/

   public void onMessage(javax.jms.Message message)
   {
      // Convert JMS message to GH Message
      count++;
      Message msg = null;
      if(null!=(msg=convertMessage(message)))
         onMessage(msg);
      else
         System.out.println("[JMSTopicMessageReceiverImpl::onMessage(javax.jms.Message)] Invalid message, skip it.");
   }

   public void closeSession(boolean unregisterListener)
   {
      try
      {
         super.closeSession(unregisterListener);
      } catch(Exception e) { e.printStackTrace(); }
   }

   public int getMessageCount()
   {
      return count;
   }

   /***********************
    *  My private method  *
    ***********************/

   private void initialize() throws NamingException, InitException
   {
      try
      {
         subscriber = null;
         if(null!=receiver)
         {
            System.out.println("[JMSTopicMessageReceiverImpl::initialize] Listening mode - register subscribter, Id : " + getId());
            subscribe(getId(), this, isDurable);
         }
      }
      catch(NamingException ne)
      {
         throw ne;
      }
      catch(Exception e)
      {
         throw new InitException("Unable to initialize message receiver : " + e.getMessage());
      }
   }

   private void writeObject(ObjectOutputStream out) throws IOException
   {
      // nothing wanna to do
   }

   private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException
   {
      log = Category.getInstance(this.getClass());
   }

   private Message convertMessage(javax.jms.Message message)
   {
      Message msg = MessageBus.createMessage();
      try
      {
         Serializable inputMsg = null;
         if(message instanceof javax.jms.TextMessage)
            inputMsg = ((javax.jms.TextMessage)message).getText();
         else if (message instanceof javax.jms.ObjectMessage)
            inputMsg = ((javax.jms.ObjectMessage)message).getObject();
         else
            System.out.println("[JMSTopicMessageReceiverImpl::convertMessage] Message type is not support, Skip this message!");

         if(null==inputMsg)
         {
            log.info("[onMessage] Null or Empty message, Skip this message!");
            return null;
         }

         msg.setSourceEngine(message.getStringProperty(Message.SOURCE_ENGINE));
         msg.setSender(message.getStringProperty(Message.SENDER));
         msg.setDestinationEngine(message.getStringProperty(Message.DESTINATION_ENGINE));
         msg.setReceiver(message.getStringProperty(Message.RECEIVER));
         msg.setRoute(message.getStringProperty(Message.ROUTE));
         msg.setReplyRoute(message.getStringProperty(Message.REPLY_ROUTE));

         msg.setPayload(inputMsg);
      }
      catch(Exception e)
      {
         e.printStackTrace();
         log.error("[onMessage] Exception happen when reveiving message from topic.");
      }
      
      return msg;
   }
}