/* Generated by Together */

package org.yang.services.messageBus.JMS;

import javax.jms.Session;
import javax.jms.QueueConnection;

public class QueueConnectionWrapper extends ConnectionWrapper
{
   static final long serialVersionUID = 3439566623980252199L;

   public QueueConnectionWrapper(JMSAdaptor adaptor) throws javax.jms.JMSException
   {
      super(adaptor);
      super.setConnection(JMSHelper.createQueueConnection(userID,
                                                          userPasswd,
                                                          factoryJNDI,
                                                          jndi_Props));
   }

   public boolean resumeConnection()
   {
      try
      {
         super.setConnection(JMSHelper.createQueueConnection(userID,
                                                             userPasswd,
                                                             factoryJNDI,
                                                             jndi_Props));
      }
      catch(Exception e)
      {
         return false;
      }

      return true;
   }

   public Session getSession(boolean shareSession, String id)
   {
      Session session = null;
      if(shareSession)
      {
         if(null==(session=(Session)this.sessions.get(this.SHARED_SESSION)))
         {
            synchronized(this)
            {
               if(null==(session=(Session)this.sessions.get(this.SHARED_SESSION)))
               {
                  try
                  {
                     session = ((QueueConnection)conn).createQueueSession(false, Session.AUTO_ACKNOWLEDGE);
                     sessions.put(this.SHARED_SESSION, session);
                  }
                  catch(Exception e)
                  {
                     //e.printStackTrace();
                     log.error(e);
                     return null;
                  }
               }
            }
         }
      }

      return session;
   }
}