/* Generated by Together */

package org.yang.services.servicemgr;
import java.util.Properties;

public class ServiceWrapperProxyc extends ServiceWrapper
{
   static final long serialVersionUID = 4711296382979764902L;

   private ServiceWrapper realWrapper = null;

   public void destroy()
   {
      //&System.out.println("[ServiceWrapperProxy::destory] Shall implement this method : class = " + this.getClass().getName());
   }

   public String getEnviromentParameter(String key)
   {
      return realWrapper.getEnviromentParameter(key);
   }

   public String getName()
   {
      return realWrapper.getName();
   }

   public String getClassName()
   {
      return realWrapper.getClassName();
   }

   public String getType()
   {
      return realWrapper.getType();
   }

   public int getGroupIDNumber()
   {
      return getGroupIDNumber();
   }

   public ServiceWrapperProxyc(ServiceWrapper realWrapper)
   {
      this.realWrapper = realWrapper;
   }

   public Area[] allAreas()
   {
      return realWrapper.allAreas();
   }

   public boolean containArea(String areaname)
   {
      return realWrapper.containArea(areaname);
   }

   public Service createServiceInstance(String domain)
   {
      return null;
   }
}