/* Generated by Together */

package org.yang.services.servicemgr;
import java.util.Set;
import java.io.Serializable;

public interface ServiceDescriptor extends Service, Serializable
{
    void setEnviromentParameter(String key, String val);
    String getEnviromentParameter(String key);

    void setName(String name);
    String getName();

    void setClassName(String className);
    String getClassName();

    void setType(String type);
    String getType();

    void setIsDisable(boolean isDisable);
    boolean getIsDisable();

    void setIsCurrent(boolean isCurrent);
    boolean getIsCurrent();

    void setGroupIDNumber(int groupIDNumber);
    int getGroupIDNumber();

    Set enviromentParameterKeys();

    Area[] allAreas();
}
