/* Generated by Together */
package org.yang.web.view.controls.jsStyle.navigationList;

import org.yang.web.view.controls.WebControl;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.jsStyle.ButtonElement;

/**
 * @testcase org.test.org.yang.web.view.controls.jsStyle.TestNavigationList 
 */
public class NavigationList extends WebControl
{
   private String id = null;
   public void setId(String id) { this.id = id; }
   public String getId() { return id; }

   protected String title = null;
   public void setTitle(String title) { this.title = title; }
   public String getTitle() { return title; }

   protected String actionLink = null;
   public void setActionLink(String actionLink) { this.actionLink = actionLink; }
   public String getActionLink() { return actionLink; }

   protected String codeBase = null;
   public void setCodeBase(String codeBase) { this.codeBase = codeBase; }

   public NavigationList(List list)
   {
      super();
      mySubcontrols.add(list);
   }

   public void addButton(ButtonElement button)
   {
      mySubcontrols.add(button);
   }

   public ButtonElement getButton(int index)
   {
      return (ButtonElement)mySubcontrols.get(index+1);
   }

   public ButtonElement removeButton(int index)
   {
      return (ButtonElement)mySubcontrols.remove(index+1);
   }

   public void addListItem(ListItem item)
   {
      ((List)mySubcontrols.get(0)).addElement(item);
   }

   public ListItem removeListItem(String id)
   {
      return ((List)mySubcontrols.get(0)).removeElement(id);
   }

   public void swap(String idFrom, String idTo)
   {
      ((List)mySubcontrols.get(0)).swap(idFrom, idTo);
   }

   public void render(JspWriter writer) throws Exception
   {
      if(null!=actionLink)
      {
         writer.println( "<form name=\"" + id + "\" action=\"" + actionLink + "\" method=\"post\" ID=\"" + id + "\">");
         writer.println( "  <input type=\"hidden\" name=\"actiontype\" value=\"\" >");
      }

      writer.println( "  <table width=\"98%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\" align=\"center\" ID=\"Table4\">");
      writer.println( "    <tr></tr>");

      if(null!=title)
      {
         writer.println( "    <tr bgcolor=\"#000066\">");
         writer.println( "      <td class=\"bigger\" background=\"" + codeBase + "/images/bar_bk.gif\">");
         writer.println( "        <font color=\"#FFFFFF\" class=\"bigger\"><b><a name=\"sec1\"></a>" + title + "</b></font>");
         writer.println( "      </td>");
         writer.println( "    </tr>");
      }

      writer.println( "    <tr>");
      writer.println( "      <td class=\"smallest\" align=\"center\" height=\"10\"></td>"); 
      writer.println( "    </tr>");
      writer.println( "    <tr bgcolor=\"#666666\">");
      writer.println( "      <td>");

      ((WebControl)mySubcontrols.get(0)).render(writer);

      writer.println( "      </td>");
      writer.println( "    </tr>");
      writer.println( "  </table>");
      writer.println( "  <table width=\"98%\" border=\"0\" cellspacing=\"0\" cellpadding=\"5\" align=\"center\" ID=\"Table6\">");
      writer.println( "    <tr valign=\"top\">");
      writer.println( "      <td class=\"smallest\" nowrap><b>");

      for(int i=1; i<mySubcontrols.size(); i++)
      {
         ((WebControl)mySubcontrols.get(i)).render(writer);
      }

      writer.println( "      </b></td>");
      writer.println( "      <td class=\"smallest\" width=\"100%\" align=\"right\"><b>");
      writer.println( "        <a href=\"#top\">");
      writer.println( "        <img src=\"" + codeBase + "/images/top.gif\" border=\"0\" alt=\"Go to top\"></a>");
      writer.println( "      </b></td>");
      writer.println( "    </tr>");
      writer.println( "  </table>");

      if(null!=actionLink)
         writer.println( "</form>");
   }
}