/* Generated by Together */

package org.yang.services.accountmgr.SimpleDAOs;

/**
 * @testcase org.test.org.yang.services.accountmgr.SimpleDAOs.TestDAOManager 
 */
public class DAOManager {
}
