/* Generated by Together */

package org.yang.services.messageBus;
import java.io.Serializable;

abstract public class Message
{
   static final long serialVersionUID = 3439575132844252199L;

   public static final int SYSTEM_MSG = 0;
   public static final int TRADE_MSG = 1;

   public static String ROUTE = "route";
   public static String REPLY_ROUTE = "reply-route";
   public static String SOURCE_ENGINE = "source-engine";
   public static String DESTINATION_ENGINE = "destination-engine";
   public static String SENDER = "sender";
   public static String RECEIVER = "receiver";

   private String route = null;
   public void setRoute(String route) { this.route=route; }
   public String getRoute() { return route; }

   private String replyRoute = null;
   public void setReplyRoute(String replyRoute) { this.replyRoute=replyRoute; }
   public String getReplyRoute() { return replyRoute; }

   int myType = 0;
   public void setType(int type) { myType=type; }
   public int getType(){ return myType; }

   String id = "";
   public void setId(String id) { this.id=id; }
   public String getId() {return id;}

   String myDestinationEngine = "";
   public void setDestinationEngine(String destinationEngine) { myDestinationEngine = destinationEngine; }
   public String getDestinationEngine() { return myDestinationEngine; }

   String myReceiver = "";
   public void setReceiver(String receiver) { myReceiver=receiver; }
   public String getReceiver() {return myReceiver;}

   String mySourceEngine = "";
   public void setSourceEngine(String sourceEngine) { mySourceEngine = sourceEngine; }
   public String getSourceEngine() { return mySourceEngine; }

   String mySender = "";
   public void setSender(String sender) { mySender=sender; }
   public String getSender() { return mySender; }

   Serializable payload = null;
   public void setPayload(Serializable payload) { this.payload = payload; }
   public Serializable getPayload() { return payload; }
}
