/* Generated by Together */

package org.yang.services.messageBus;

public interface MessageTransmitter
{
   static final long serialVersionUID = 3439536460444252199L;

   public void transmit(Message msg) throws MessageTransmitException;
   
   public int getMessageCount();
}
