/* Generated by Together */

package org.yang.services.messageBus;

/**
 * @stereotype exception 
 */
public class NoRoutingTableException extends InitException
{
   static final long serialVersionUID = 3439536529488252199L;
   
   public NoRoutingTableException()
   {
      super();	
   }

   public NoRoutingTableException(String s)
   {
      super(s);	
   }
}
