/* Generated by Together */

package org.yang.customized.gtf.services.scheduler.web;
import javax.servlet.jsp.PageContext;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.WebControl;
import java.util.ArrayList;
import java.util.Iterator;

public class FutureTasks extends DaySchedule
{
   private String id = null;
   public void setId(String id) { this.id = id; }

   private String title = "Month/Date(Day)";
   public void setTitle(String title) { this.title = title; }

   private String actionLink = null;
   public void setActionLink(String actionLink) { this.actionLink = actionLink; }

   private String bgcolor = "'#FFFFFF'";
   public void setBgcolor(String bgcolor) { this.bgcolor = bgcolor; }

   private String titleColor = "'#000000'";
   public void setTitleColor(String titleColor) { this.titleColor = titleColor; }

   private String imageCodeBase = null;
   public void setImageCodeBase(String imageCodeBase) { this.imageCodeBase = imageCodeBase; }

   public FutureTasks() {}

   public void render(JspWriter writer) throws Exception
   {
      writer.println("           <tr>");
      writer.println("             <td><img src='"+ imageCodeBase +"/spacer.gif' alt='' width='10' height='80' /></td>");
      writer.println("             <td valign='top' colspan='7' bgcolor='"+bgcolor+"' style='border:solid 1px green; background-color:white;;background-color:"+bgcolor+"'>");
      writer.println("                <table cellpadding='0' cellspacing='2' style='margin:0px;'>");
      writer.println("                  <tr>");
      writer.println("                    <td><img src='"+ imageCodeBase +"/spacer.gif' alt='' border='0' width='120' height='4' /></td>");
      writer.println("                    <td><img src='"+ imageCodeBase +"/spacer.gif' alt='' border='0' width='360' height='4' /></td>");
      writer.println("                  </tr>");
      writer.println("                </table>");

      writer.println("                <table border='1' cellspacing='0' cellpadding='3' bordercolorlight='#cccccc' bordercolor='#cccccc'");
      writer.println("                       bordercolordark='#ffffff' bgcolor='#eaeaea' align='center' width='95%' ID='Table3'>");
      writer.println("                  <tr bgcolor='#ffffff'>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>Item</font></b>");
      writer.println("                    </td>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>Quan.</font></b>");
      writer.println("                    </td>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>Strain</font></b>");
      writer.println("                    </td>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>Order</font></b>");
      writer.println("                    </td>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>PMS</font></b>");
      writer.println("                    </td>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>HCG/Mate</font></b>");
      writer.println("                    </td>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>Plug Date</font></b>");
      writer.println("                    </td>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>User Name</font></b>");
      writer.println("                    </td>");
      writer.println("                    <td nowrap class='smaller' align='center'>");
      writer.println("                      <b><font color='#2a00aa'>phone</font></b>");
      writer.println("                    </td>");
      writer.println("                  </tr>");

      Iterator it = this.subcontrols();
      FutureTask task = null;
      while(it.hasNext())
      {
         ((FutureTask)it.next()).render(writer);
      }

      writer.println("                </table>");

      writer.println("                <table cellpadding='0' cellspacing='2' style='margin:0px;'>");
      writer.println("                  <tr>");
      writer.println("                    <td><img src='"+ imageCodeBase +"/spacer.gif' alt='' border='0' width='120' height='4' /></td>");
      writer.println("                    <td><img src='"+ imageCodeBase +"/spacer.gif' alt='' border='0' width='360' height='4' /></td>");
      writer.println("                  </tr>");
      writer.println("                </table>");

      writer.println("              </td>");
      writer.println("            </tr>");
   }
}
