/* Generated by Together */
package org.yang.web.view.controls.jsStyle.navigationList;

import org.yang.web.view.controls.WebControl;
import javax.servlet.jsp.JspWriter;

/**
 * @testcase org.test.org.yang.web.view.controls.jsStyle.TestList 
 */
public class List extends WebControl
{
   protected String codeBase = null;
   public void setCodeBase(String codeBase) { this.codeBase = codeBase; }

   protected String actionLink = null;
   public void setActionLink(String actionLink) { this.actionLink = actionLink; }
   public String getActionLink() { return actionLink; }

   public List()
   {
      super();
   }

   public void addElement(ListItem item)
   {
      addASubcontrol(item);
   }

   public ListItem removeElement(String id)
   {
      if(null==id)
        return null;
      for(int i=mySubcontrols.size()-1; i>=0; i--)
      {
         ListItem element = (ListItem)mySubcontrols.get(i);
         if(id.equals(element.getId()))
         {
            return (ListItem)mySubcontrols.remove(i);
         }
      }
      return null;
   }

   public void swap(String idFrom, String idTo)
   {
      if(null==idFrom||null==idTo)
         return;

      int indexFrom = -1;
      int indexTo = -1;
      ListItem objFrom = null;
      ListItem temp = null;
//&System.out.println("----------------->" + idFrom + "--->" + idTo);
      for(int i=0; i<mySubcontrols.size(); i++)
      {
         temp = (ListItem)mySubcontrols.get(i);
//&System.out.println("-------------->" + temp.getId() + "--->" + i);
         if(idFrom.equals(temp.getId()))
         {
//&System.out.println("Got indexFrom ->" + indexFrom);
            indexFrom = i;
            objFrom = (ListItem)mySubcontrols.get(i);
         }

         if(idTo.equals(temp.getId()))
         {
//&System.out.println("Got indexTo ->" + indexTo);
            indexTo = i;
         }
      }

      if(-1!=indexFrom&&-1!=indexTo)
      {
         mySubcontrols.set(indexFrom, mySubcontrols.get(indexTo));
         mySubcontrols.set(indexTo, objFrom);
      }
   }

   public void render(JspWriter writer) throws Exception
   {
      writer.println( "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\" bgcolor=\"#ffffff\" ID=\"Table5\">");
      for(int i=0; i<mySubcontrols.size(); i++)
      {
         if(0==i%2)
           ((ListItem)mySubcontrols.get(i)).setColor("#e9e9e9");
         else
           ((ListItem)mySubcontrols.get(i)).setColor("#ffffff");
      }
      this.renderSubcontrols(writer);
      writer.println( "</table>" );
   }
}