/* Generated by Together */
package org.yang.web.services.domainManage;
import org.yang.web.view.controls.WebControlBuilder;
import org.yang.web.view.controls.WebControl;
import org.yang.web.controller.GenericBean;
import org.yang.services.domainMgr.Domain;
import org.yang.web.view.controls.jsStyle.WebControlGroup;
import org.yang.web.view.controls.jsStyle.misc.MessageDisplayingBanner1;
import org.yang.web.view.controls.jsStyle.UIForm;
import org.yang.web.view.controls.jsStyle.TextField;
import org.yang.web.view.controls.jsStyle.TextAreaElement;
import org.yang.services.dataAccess.DataGroup;
import org.yang.services.dataAccess.Data;
import java.util.Iterator;
import org.yang.web.view.controls.jsStyle.ButtonElement;



public class DomainInformationFormBuilder implements WebControlBuilder
{
   public WebControl build(GenericBean bean) throws Exception
   {
      DomainInformationBean domainBean = (DomainInformationBean)bean;
      String codeBase = domainBean.getAppBase() + domainBean.getGuiBase();
      Domain currentDomain = domainBean.getCurrentDomain();

      WebControlGroup controlGroup = new WebControlGroup();

      if(GenericBean.ERR==domainBean.getState())
      {
         MessageDisplayingBanner1 banner = new MessageDisplayingBanner1();
         banner.setText(domainBean.getMsg());//"Some required field is empty, Please submit it again.");
         banner.setColor("#cc0000");
         controlGroup.addASubcontrol(banner);
      }

      UIForm form = new UIForm();
      form.setCaption("Basic Information");

      TextField projectId = new TextField();
      projectId.setTitle("Domain ID");
      projectId.setId("datas_id");
      projectId.setName("datas_id");
      projectId.setValue((String)currentDomain.get(currentDomain.getPrimaryKey()));
      if(Domain.CREATE!=currentDomain.getAction())
         projectId.setIsReadOnly(true);
      form.addASubcontrol(projectId);


      String[] columns = currentDomain.displayColumns();
      String[] titles = currentDomain.displayColumnNames();
      String[] controls = currentDomain.displayControlElements();
      TextField field = null;
      TextAreaElement area = null;
      for(int i=0; i<columns.length; i++)
      {
         if("text field".equals(controls[i]))
         {
            field = new TextField();
            field.setTitle(titles[i]);
            field.setId("datas_" + columns[i]);
            field.setName("datas_" + columns[i]);
            field.setValue((String)currentDomain.get(columns[i]));
            form.addASubcontrol(field);
         }
         else if("text area".equals(controls[i]))
         {
            area = new TextAreaElement();
            area.setTitle(titles[i]);
            area.setId("datas_" + columns[i]);
            area.setName("datas_" + columns[i]);
            area.setValue((String)currentDomain.get(columns[i]));
            form.addASubcontrol(area);
         }
      }

      controlGroup.addASubcontrol(form);

      ButtonElement save = new ButtonElement();
      if(Domain.CREATE==currentDomain.getAction())
      {
         save.setAction("javascript:submitForm('domainInformation','create')");
         save.setAlt("Create domain");
         save.setName("save");
         save.setOffIcon(codeBase + "/images/English/btn_create.gif");
         save.setOnIcon(codeBase + "/images/English/btn_create_on.gif");
         form.addAButton(save);
      }
      else
      {
         save.setAction("javascript:submitForm('domainInformation','update')");
         save.setAlt("Update domain information");
         save.setName("save");
         save.setOffIcon(codeBase + "/images/English/btn_update.gif");
         save.setOnIcon(codeBase + "/images/English/btn_update_on.gif");
         form.addAButton(save);
      }

      ButtonElement help = new ButtonElement();
      help.setAction("javascript:top.topFrame.openSWHelpWindow('" + codeBase + "/help/English/help.jsp?right=schedule.htm#project')");
      help.setName("help");
      help.setOffIcon(codeBase + "/images/English/btn_help.gif");
      help.setOnIcon(codeBase + "/images/English/btn_help_on.gif");
      help.setAlt("Help");
      form.addAButton(help);

      return controlGroup;
   }
}