/* Generated by Together */
package org.yang.customized.gtf.services.inventoryManager.web;

import org.yang.web.view.controls.WebControl;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.jsStyle.SelectElement;

/**
 * @testcase org.test.org.yang.web.view.controls.jsStyle.TestNavigationList 
 */
public class StorageSearchControl extends WebControl
{
   private String id = null;
   public void setId(String id) { this.id = id; }
   public String getId() { return id; }

   protected String actionLink = null;
   public void setActionLink(String actionLink) { this.actionLink = actionLink; }
   public String getActionLink() { return actionLink; }

   protected String target = null;
   public void setTarget(String target) { this.target = target; }
   public String getTarget() { return target; }

   protected String codeBase = null;
   public void setCodeBase(String codeBase) { this.codeBase = codeBase; }

   private String searchKeys = "";
   public void setSearchKeys(String searchKeys){ this.searchKeys = searchKeys; }

   private SelectElement investigatorSelector = null;
   public void setInvestigatorSelector(SelectElement investigatorSelector) { this.investigatorSelector = investigatorSelector; }

   private SelectElement labSelector = null;
   public void setLabSelector(SelectElement labSelector) { this.labSelector = labSelector; }

   public StorageSearchControl()
   {
      super();
   }

   public void render(JspWriter writer) throws Exception
   {
	  writer.println("<tr>");
	  writer.println("  <td>");
      writer.println("<STYLE type=\"text/css\" \">");
      writer.println("OPTION.style2{background-color:#A9A9F5; color:black;width:90px}");
      writer.println("OPTION.style1{background-color:white; color:black;width:90px}");
      writer.println("</STYLE>");
   	
      writer.println( "    <script language=\"JavaScript\" type=\"text/javascript\">");
      writer.println( "      //---------------------------------------");
      writer.println( "      function submitForm(frm, act) {");
      //writer.println( "        alert('act='+act);");
      writer.println( "        fm = eval('document.'+ frm);");
      writer.println( "        fm.actiontype.value = act;");
      writer.println( "        fm.target = '"+target+"';");
      writer.println( "        if('updateDomain'==act||'updateData'==act){");
      writer.println( "        fm.action = '/wf/storageSearch.wf';");
      writer.println( "        fm.target ='_self';");
          
      writer.println( "        }");
      
      writer.println( "        fm.submit();");
      writer.println( "      }");
      writer.println( "    </script>");
      writer.println( "        <script language=\"JavaScript\" type=\"text/javascript\">");
      writer.println( "        //---------------------------------------");
      writer.println( "        function submitFormThenTargetTo(frm, act, tar) {");
      writer.println( "          fm = eval('document.'+ frm);");
      writer.println( "          fm.actiontype.value = act;");
      writer.println( "          fm.target = tar;");

      writer.println( "          if(act=='clear'){");
      writer.println( "          //alert('fm.labName.value ='+ fm.labName.value);");
      writer.println( "          fm.labName.value = '  Please select';");
      writer.println( "          fm.investigator.value = '  Please select';");
      writer.println( "          fm.searchKeys.value = '';");
      writer.println( "          }");

       
      writer.println( "          fm.submit();");
      writer.println( "        }");
      writer.println( "        </script>");

      writer.println( "      <form name=\"" + id + "\" method=\"post\" action=\"" + actionLink + "\" target=\"" + target + "\" ID=\"" + id + "\">");
      writer.println( "      <table width=\"100%\" border=\"1\" cellspacing=\"0\" cellpadding=\"3\" bordercolorlight=\"#cccccc\" bordercolor=\"#cccccc\" bordercolordark=\"#ffffff\" bgcolor=\"#eaeaea\" align=\"center\" ID=\"Table4\">");
      writer.println( "        <input type=\"hidden\" name=\"actiontype\" value=\"\" id=\"actiontype.hidden\">");

      if(null!=labSelector)
      {
         labSelector.setOnChange("javascript:submitForm('searchControl', 'updateDomain')");
         writer.println( "        <tr>");
         writer.println( "          <td nowrap align=\"left\" class=\"smallest\" height=\"6\">");
         writer.println( "            <FONT color=\"#000060\">Lab&nbsp;Name :&nbsp;&nbsp;&nbsp;</FONT>");
         labSelector.printBody(writer);
         writer.println( "          </td>");
         writer.println( "        </tr>");
      }

      

      if(null!=investigatorSelector)
      {
         investigatorSelector.setOnChange("javascript:submitForm('searchControl', 'updateData')");
         writer.println( "        <tr>");
         writer.println( "          <td nowrap align=\"left\" class=\"smallest\">");
         writer.println( "            <font color=\"#000060\">Investigator :</font>");
         investigatorSelector.printBody(writer);
         writer.println( "          </td>");
         writer.println( "        </tr>");
      }


      //writer.print("      </form>");
      
      
      writer.println( "        <tr>");
      writer.println( "          <td nowrap align=\"left\" class=\"smallest\" height=\"6\">");
      writer.println( "            <font color=\"#000060\">Keywords :&nbsp;&nbsp;&nbsp;</font>");
      writer.println( "            <input type=\"text\" name=\"searchKeys\" value=\"" + searchKeys + "\" size=\"16\" ID=\"Text1\"\">");  //onChange=\"javascript:submitForm('updateData', 'updateData')\">");
      writer.println( "          </td>");
      writer.println( "        </tr>");

      writer.println( "        <TR>");
      writer.println( "          <TD class=\"smallest\" noWrap align=\"left\">");

      this.renderSubcontrols(writer);

      writer.println( "          </TD>");
      writer.println( "        </TR>");
      writer.println( "        </form>");

      writer.println( "      </table>");
	  writer.println("  </td>");
	  writer.println("</tr>");

   }
}