/* Generated by Together */
package org.yang.web.view.controls.jsStyle.dataSheet;

import org.yang.web.view.controls.WebControl;
import javax.servlet.jsp.JspWriter;
import java.util.HashMap;
import java.util.Iterator;

/**
 * @testcase org.test.org.yang.web.view.controls.jsStyle.TestNavigationList 
 */
public class DataSheetSet extends WebControl
{
   protected HashMap dataSheetTable = null;

   protected String id = null;
   public void setId(String id) { this.id = id; }
   public String getId() { return id; }

   protected String text = null;
   public void setText(String text) { this.text = text; }
   public String getText() { return text; }

   protected String highlightId = null;
   public void setHighlightId(String highlightId) { this.highlightId = highlightId; }

   protected String highlightColor = "#FFFF00";
   public void setHighlightColor(String highlightColor) { this.highlightColor = highlightColor; }

   protected boolean isVertical = true;
   public void setIsVertical(boolean isVertical) { this.isVertical = isVertical; }

   protected String codeBase = null;
   public void setCodeBase(String codeBase) { this.codeBase = codeBase; }

   public DataSheetSet()
   {
      super();
      dataSheetTable = new HashMap();
   }

   public void addDataSheet(DataSheet dataSheet)
   {
      mySubcontrols.add(dataSheet);
      dataSheetTable.put(dataSheet.getId(), dataSheet);
   }

   public DataSheet getDatasheet(String key)
   {
      return (DataSheet)dataSheetTable.get(key);
   }

   public void render(JspWriter writer) throws Exception
   {
      Iterator it = subcontrols();
      DataSheet control = null;
      if(!isVertical)
      {
         writer.print("<table align=\"left\">");
         writer.print("<tr>");
         while(it.hasNext())
         {
            control = (DataSheet)it.next();
            control.setHighlightId(highlightId);
            control.setHighlightColor(highlightColor);
            writer.print("<td>");
            control.render(writer);
            writer.print("</td>");
         }
         writer.print("</tr>");
         writer.print("</table>");
      }
      else
      {
         while(it.hasNext())
         {
            control = (DataSheet)it.next();
            control.setHighlightId(highlightId);
            control.setHighlightColor(highlightColor);
         }
         this.renderSubcontrols(writer);
      }
   }
}