/* Generated by Together */
package org.yang.customized.gtf.services.projectManager.web;

import org.yang.web.view.controls.WebControlBuilder;
import org.yang.web.view.controls.WebControl;
import org.yang.web.controller.GenericBean;
import org.yang.web.view.controls.jsStyle.UIForm;
import org.yang.web.view.controls.jsStyle.TextField;
import org.yang.web.view.controls.jsStyle.PassElement;
import org.yang.web.view.controls.jsStyle.SelectElement;
import org.yang.web.view.controls.jsStyle.TextAreaElement;
import org.yang.web.view.controls.jsStyle.ButtonElement;
import org.yang.web.view.controls.jsStyle.InformationForm;
import java.util.HashMap;
import java.util.Iterator;
import org.yang.customized.gtf.services.dataAccess.Project;
import org.yang.web.view.controls.jsStyle.WebControlGroup;
import org.yang.services.dataAccess.DataGroup;
import org.yang.services.dataAccess.Data;
import org.yang.web.view.controls.jsStyle.FileUpload;
import org.yang.web.view.controls.jsStyle.TextButtonElement;

public class PhotoUploadFormBuilder implements WebControlBuilder
{
   public WebControl build(GenericBean bean) throws Exception
   {
      PhotoUploadBean projectBean = (PhotoUploadBean)bean;
      String codeBase = projectBean.getAppBase() + projectBean.getGuiBase();

      WebControlGroup controlGroup = new WebControlGroup();

      InformationForm form = new InformationForm();
      form.setCaption("Photo upload form");
      form.setActionLink(projectBean.getAppBase() + "/fileAccess.wf");
      form.setId("fileUpload");
      form.setIsMultipart(true);

      TextField filename = new TextField();
      filename.setTitle("Project type");
      filename.setId("filename");
      filename.setName("filename");
      filename.setValue(projectBean.getPhotoId());
      filename.setIsReadOnly(true);
      form.addASubcontrol(filename);

      FileUpload fileUpload = new FileUpload();
      fileUpload.setTitle("Select photo file");
      fileUpload.setId("fileUpload");
      fileUpload.setName("fname");
      form.addASubcontrol(fileUpload);

      //ButtonElement save = new ButtonElement();
      //save.setAction("javascript:submitForm('fileUpload','update')");
      //save.setAlt("Upload photo to server");
      //save.setName("submit");
      //save.setOffIcon(codeBase + "/images/English/btn_update.gif");
      //save.setOnIcon(codeBase + "/images/English/btn_update_on.gif");
      TextButtonElement save = new TextButtonElement();
      save.setText("Upload photo");
      form.addAButton(save);

      controlGroup.addASubcontrol(form);

      return controlGroup;
   }
}