/* Generated by Together */

package org.yang.customized.gtf.services.scheduleManager.web;

import org.yang.web.applicationContainer.SecuredBean;
import org.yang.customized.gtf.services.scheduleManager.ScheduleManager;

abstract public class ScheduleBean extends SecuredBean
{
   static final long serialVersionUID = 4711296382979764901L;

   protected transient ScheduleManager scheduleMgr = null;

   public ScheduleBean()
   {
      super();
   }

   /***************************************
    *  Implement GenericHandler's method  *
    ***************************************/

   protected void ensureResource() throws Exception
   {
      System.out.println("[ScheduleBean::ensureResource] entering!");

      if(null==scheduleMgr)
         scheduleMgr = (ScheduleManager)passport.loadService("ScheduleManager");
   }
}