/* Generated by Together */

package org.yang.web.services.accountManage;

import org.yang.web.applicationContainer.SecuredBean;
import org.yang.services.accountmgr.UserManager;

abstract public class AccountBean extends SecuredBean
{
   protected transient UserManager userMgr = null;

   public AccountBean()
   {
      super();
   }

   /***************************************
    *  Implement GenericHandler's method  *
    ***************************************/
   protected void ensureResource() throws Exception
   {
      if(null==userMgr)
         userMgr = (UserManager)passport.loadService("AccountManager");
   }
}