/* Generated by Together */
package org.yang.web.services.accountManage;

import org.yang.web.view.controls.WebControlBuilder;
import org.yang.web.view.controls.WebControl;
import org.yang.web.controller.GenericBean;
import org.yang.web.view.controls.jsStyle.UISelector;
import org.yang.web.view.controls.jsStyle.ButtonElement;
import org.yang.services.accountmgr.User;
import org.yang.web.applicationContainer.SelectorItem;
import org.yang.web.view.controls.jsStyle.DummyControl;

public class GroupUserInfoBuilder implements WebControlBuilder
{
   public WebControl build(GenericBean bean) throws Exception
   {
      GroupBean groupBean = (GroupBean)bean;
      if("clear".equals(groupBean.getLastActiontype()))
      {
         return new DummyControl();
      }

      String codeBase = groupBean.getAppBase() + groupBean.getGuiBase();
      UISelector selector = new UISelector();
      selector.setName("members");
      selector.setNote("users");
      selector.setCaption("Users");
      selector.setNote("Note: If you remove a user from a group and they are currently logged in, they will be logged out of the system.");
      selector.setAddIcon(codeBase + "/images/right_arrow.gif");
      selector.setAddAction("javascript:validateForm('group_form','selectMembers',reqA)");
      selector.setAddCaption("Add users");
      selector.setSelectedBoxCaption("Members");
      selector.setRemoveIcon(codeBase + "/images/left_arrow.gif");
      selector.setRemoveAction("javascript:validateForm('group_form','deselectMembers',reqA)");
      selector.setRemoveCaption("Remove users");
      selector.setUnselectedBoxCaption("Nonmembers");

      User[] members = groupBean.getMembers();
      SelectorItem[] items = new SelectorItem[members.length];
      for(int i=0; i<members.length; i++)
      {
         items[i] = new SelectorItem();
         items[i].setId(members[i].getID());
         items[i].setValue(members[i].getID());
      }
      selector.setSelectedItems(items);

      User[] nonmembers = groupBean.getNonmembers();
      items = new SelectorItem[nonmembers.length];
      for(int i=0; i<nonmembers.length; i++)
      {
         items[i] = new SelectorItem();
         items[i].setId(nonmembers[i].getID());
         items[i].setValue(nonmembers[i].getID());
      }
      selector.setUnselectedItems(items);

      ButtonElement help = new ButtonElement();
      help.setAction("javascript:top.topFrame.openSWHelpWindow('" + codeBase + "/help/English/help.jsp?right=admin_user.htm#group')");
      help.setName("help");
      help.setOffIcon(codeBase + "/images/English/btn_help.gif");
      help.setOnIcon(codeBase + "/images/English/btn_help_on.gif");
      help.setAlt("Help");
      selector.addAButton(help);
      return selector;
   }
}