/* Generated by Together */

package org.yang.util.template;
import java.util.Date;
import java.text.SimpleDateFormat;

public class DateTimeFormatter
{
   private static SimpleDateFormat format
            = new SimpleDateFormat ("yyyy-MM-dd'T'HH:mm:ss");

   public static String getDateTimeString(Date date)
   {
      return format.format(date);
   }
}
