/* Generated by Together */

package org.yang.services.messageBus;

/**
 * @stereotype exception 
 */
public class DataReceivingException extends Exception
{
   static final long serialVersionUID = 3439536529432452199L;
   
   public DataReceivingException()
   {
      super();	
   }

   public DataReceivingException(String s)
   {
      super(s);	
   }
}
