/* Generated by Together */

package org.yang.web.view.controls;
import java.util.Hashtable;

public class WebControlBuilderFactory
{
   private static Hashtable webControls = new Hashtable();
   private static WebControlBuilderFactory factory = new WebControlBuilderFactory();

   private WebControlBuilderFactory() {}

   public static WebControlBuilderFactory getFactory()
   {
      return factory;
   }

   public WebControlBuilder createBuilder(String className)
   {
      Object temp = null;
      if(null==(temp=webControls.get(className)))
      {
         synchronized(this)
         {
            if(null==(temp=webControls.get(className)))
            {
                try
                {
                   temp = (WebControlBuilder)Class.forName(className).newInstance();
                }
                catch(Exception e)
                {
                   e.printStackTrace();
                }
            }
         }
      }

      return (WebControlBuilder)temp;
   }
}