/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.JspWriter;

public class Photo extends FormElement 
{
   private ButtonElement pickPhoto = null;
   private ButtonElement confirm = null;
   private ButtonElement browse = null;
   private ButtonElement delete = null;

   public Photo() {}

   private String id = null;
   public void setId(String id) { this.id = id; }

   private String name = null;
   public void setName(String name) { this.name = name; }

   private String value = null;
   public void setValue(String value) { this.value = value; }

   private String action = null;
   public void setAction(String action) { this.action = action; }

   private String uploadAction = null;
   public void setUploadAction(String uploadAction) { this.uploadAction = uploadAction; }

   private String confirmAction = null;
   public void setConfirmAction(String confirmAction) { this.confirmAction = confirmAction; }

   private String browseAction = null;
   public void setBrowseAction(String browseAction) { this.browseAction = browseAction; }

   private String deleteAction = null;
   public void setDeleteAction(String deleteAction) { this.deleteAction = deleteAction; }

   private String codeBase = "/wf/default";
   private void setCodeBase(String codeBase) { this.codeBase = codeBase; }

   private boolean hasPhoto = true;
   public void setHasPhoto(boolean hasPhoto) { this.hasPhoto = hasPhoto; }

   private String alt = null;
   public void setAlt(String alt) { this.alt = alt; }

   protected void printBody(JspWriter writer) throws Exception
   {
      writer.println("<script language=\"JavaScript\" type=\"text/javascript\">");
      writer.println("		function openWin (url, w, h)");
      writer.println("		{");
      writer.println("			var swWidth = 780;");
      writer.println("			var swHeight = 520;");
      writer.println("			var peekWin = window.open(url,\"NotifyWindow\",\"width=\"+swWidth+\",height=\"+swHeight+\",menubar=no,toolbar=no,resizable=yes,status=yes\");");
      writer.println("			///peekWin.moveTo((screen.availWidth/2)-(w/2),(screen.availHeight/2)-(h/2));");
      writer.println("			peekWin.focus();");
      writer.println("			///peekWin.location.reload();");
      writer.println("		}");
      writer.println("	</script>");

      if(!hasPhoto)
      {
         pickPhoto = new ButtonElement();
         pickPhoto.setAlt(alt);
         pickPhoto.setAction("javascript:openWin('" + uploadAction  + "', 500, 550)");
         pickPhoto.setName(name);
         pickPhoto.setOffIcon(codeBase + "/images/English/btn_upload.gif");
         pickPhoto.setOnIcon(codeBase + "/images/English/btn_upload_on.gif");
         pickPhoto.render(writer);

         confirm = new ButtonElement();
         confirm.setAlt(alt);
         confirm.setAction( confirmAction );
         confirm.setName(name);
         confirm.setOffIcon(codeBase + "/images/English/btn_approved.gif");
         confirm.setOnIcon(codeBase + "/images/English/btn_approved_on.gif");
         confirm.render(writer);
      }
      else
      {
         writer.print("<b><font color = \"#0000cc\">" + value + "</font></b>");
         browse = new ButtonElement();
         browse.setAlt(alt);
         browse.setAction("javascript:openWin('" + browseAction + "', 500, 550)");
         browse.setName(name);
         browse.setOffIcon(codeBase + "/images/English/btn_browse.gif");
         browse.setOnIcon(codeBase + "/images/English/btn_browse_on.gif");
         browse.render(writer);

         delete = new ButtonElement();
         delete.setAlt(alt);
         delete.setAction( deleteAction );
         delete.setName(name);
         delete.setOffIcon(codeBase + "/images/English/btn_remove.gif");
         delete.setOnIcon(codeBase + "/images/English/btn_remove_on.gif");
         delete.render(writer);
      }
   }
}