/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.JspWriter;
import java.util.Arrays;

public class Select extends GenericControl 
{
   private SelectOption selectedOption = null;

   private String id = null;
   public void setId(String id) { this.id = id; }

   private String name = null;
   public void setName(String name) { this.name = name; }
   public String getName() { return name; }

   private String[] values = null;
   public void setValues(String[] values) { this.values = values; }

   private String unit = null;
   public void setUnit(String unit) { this.unit = unit; }

   private String[] displayNames = null;
   public void setDisplayNames(String[] displayNames) { this.displayNames = displayNames; }

   private String selectedValue = null;
   public void setSelectedValue(String selectedValue) { this.selectedValue = selectedValue; }
   public String getSelectedValue() { return selectedValue; }

   private String onChange = null;
   public void setOnChange(String onChange) { this.onChange = onChange; }

   private String size = "1";
   public void setSize(String size) { this.size = size; }

   private boolean isAction = false;
   public void setIsAction(boolean isAction) { this.isAction = isAction; }

   private String actionLink = null;
   public void setActionLink(String actionLink) { this.actionLink = actionLink; }
   public String getActionLink() { return actionLink; }

   private boolean displayOnly = false;
   public void setDisplayOnly(boolean displayOnly) { this.displayOnly = displayOnly; }

   private boolean doSort = true;
   public void setDoSort(boolean doSort){this.doSort=doSort;}
   public boolean getDoSort(){return doSort;}

   public void printBody(JspWriter writer) throws Exception
   {
      SelectOption[] options = new SelectOption[values.length];
      
      for(int i=0; i<values.length; i++)
      {
         options[i] = new SelectOption();
         options[i].setId(values[i]);
         if(values[i]==null)
            values[i]="N/A";
            
         if(null!=displayNames&&
            i<displayNames.length)
            options[i].setDisplayName(displayNames[i]);
         else         
            options[i].setDisplayName(values[i]);

         if(values[i].equals(selectedValue))
         {
            options[i].setIsSelected(true);
            selectedOption = options[i];
         }
      }
      
      if(displayOnly)
      {
         writer.print("<b><font color = \"#000000\">" + selectedOption.getDisplayName() + "</font></b>");
         return;
      }

      if(isAction)
         writer.print("<form  name=\"" + name + "\" action=\"" + actionLink + "\" method=\"post\" id=\"" + id + "\">");

      writer.print("    <select id=\"" + id + "\"");
      writer.print("            size=\"" + size + "\"");
      writer.print("            onChange=\"" + onChange + "\"");
      writer.print("            name=\"" + name + "\">");

      if(1<options.length&&doSort)
         Arrays.sort(options);
      if(null==selectedOption)
      {
         writer.print("      <option value=\"" + selectedValue + "\" selected>" + selectedValue + "</option>");
      }

      for(int i=0; i<options.length; i++)
      {
         options[i].printBody(writer);
      }

      writer.print("    </select>");
      if(null!=unit)
         writer.print(" " + unit);
      if(isAction)
         writer.print("</form>");
   }

   public void printBodyx(JspWriter writer) throws Exception
   {
      if(displayOnly)
      {
         String displayValue = null;
         for(int i=0; i<values.length; i++)
         {
            if(values[i].equals(selectedValue))
               displayValue = displayNames[i];
         }
         writer.print("<b><font color = \"#000000\">" + displayValue + "</font></b>");
         return;
      }

      boolean gotCurrentValue = false;
      if(null==displayNames)
         displayNames = values;

      if(isAction)
         writer.print("<form  name=\"" + name + "\" action=\"" + actionLink + "\" method=\"post\" id=\"" + id + "\">");

      writer.print("    <select id=\"" + id + "\"");
      writer.print("            size=\"" + size + "\"");
      writer.print("            onChange=\"" + onChange + "\"");
      writer.print("            name=\"" + name + "\">");
      for(int i=0; i<values.length; i++)
      {
         writer.print("      <option value=\"" + values[i] + "\" ");
         if(selectedValue.equals(values[i]))
         {
            writer.print("selected");
            gotCurrentValue = true;
         }
         writer.print(">" + displayNames[i] + "</option>");
      }

      if(!gotCurrentValue)
      {
         writer.print("      <option value=\"" + selectedValue + "\" selected>" + selectedValue + "</option>");
      }

      writer.print("    </select>");
      if(null!=unit)
         writer.print(" " + unit);
      if(isAction)
         writer.print("</form>");
   }
}