/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.WebControl;

public class ServiceListElement extends WebControl
{
   private String id = null;
   public void setId(String id) { this.id = id; }

   private String name = null;
   public void setName(String name) { this.name = name; }

   private String value = null;
   public void setValue(String value) { this.value = value; }

   private String caption = null;
   public void setCaption(String caption) { this.caption = caption; }

   private String icon = null;
   public void setIcon(String icon) {  this.icon = icon; }

   private String configButtonAction = null;
   public void setConfigButtonAction(String configButtonAction) { this.configButtonAction = configButtonAction; }

   private String configButtonIcon = null;
   public void setConfigButtonIcon(String configButtonIcon) { this.configButtonIcon = configButtonIcon; }

   private boolean isConfigurable = false;
   public void setIsConfigurable(boolean isConfigurable) { this.isConfigurable = isConfigurable; }

   private boolean isSingle = true;
   public void setIsSingle(boolean isSingle) { this.isSingle = isSingle; }

   private boolean isChecked = false;
   public void setIsChecked(boolean isChecked) { this.isChecked = isChecked; }

   public void render(JspWriter writer) throws Exception
   {
      //writer.println("<script language=\"JavaScript\" type=\"text/javascript\">");
      //writer.println("  function setChkService(frm, act, serv, ary)");
      //writer.println("  {");
      //writer.println("    fm = eval('document.'+ frm);");
      //writer.println("    chks = fm.services;");
      //writer.println("    isChecked = false;");
      //writer.println("    if (chks.length){");
      //writer.println("      for(i=0; i<chks.length; i++) {");
      //writer.println("        if (chks[i].checked)");
      //writer.println("          if (chks[i].value==serv)");
      //writer.println("            isChecked = true;");
      //writer.println("      }");
      //writer.println("    }");
      //writer.println("    if (isChecked) {");
      //writer.println("      if (checkFieldRequired(frm,ary)){");
      //writer.println("        fm.editservice.value=serv;");
      //writer.println("        submitForm(frm,act);");
      //writer.println("      }");
      //writer.println("    }");
      //writer.println("    else");
      //writer.println("      alert('This group does not have permissions for this service.  To give this group permission, click the checkbox next to the service name and try again.');");
      //writer.println("  }");
      //writer.println("</script>");

      writer.println("<tr>");
      writer.println("  <td bgcolor=\"#CCCCCC\">");

      String checked = "";
      if(isChecked)
         checked = "checked";

      String type = "";
      if(isSingle)
         type = "radio";
      else
         type = "checkbox";

      writer.println("    <input type=\"" + type + "\" name=\"" + name + "\" value=\"" + value + "\" ID=\"" + id + "\" " + checked + ">");
      writer.println("  </td>");
      writer.println("  <td nowrap class=\"bigger\">");
      writer.println("    <img src=\"" + icon + "\" align=\"absmiddle\">");
      writer.println("    <b> " + caption + "</b>");
      writer.println("  </td>");
      writer.println("  <td width=\"100%\">");
      writer.println("    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" ID=\"Table12\">");

      if(null==configButtonAction)
         writer.print(" --- ");
      else
         this.renderSubcontrols(writer);

      writer.println("    </table>");
      writer.println("  </td>");

      if(isConfigurable)
      {
         writer.println("  <td align=\"center\">");
         if(null==configButtonAction)
         {
            writer.print(" - ");
         }
         else
         {
            writer.println("    <a href=\"" + configButtonAction + "\">");
            writer.println("	  <img src=\"" + configButtonIcon + "\" border=\"0\")>");
            writer.println("    </a>");
         }
         writer.println("  </td>");
      }

      writer.println("</tr>");
   }

/*
			<tr>
				<td bgcolor="#CCCCCC">
					<input type="checkbox" 
						   name="services" 
						   value="EditorsDesk" 
						   ID="Checkbox4">
				</td>
				<td nowrap class="bigger">
					<img src="/actrellis/defaultskin/images/small_ico_EditorsDesk.gif" align="absmiddle">
					<b>	Editor's Desk &nbsp;</b>
				</td>
				<td nowrap class="smaller">
					No sections selected
				</td>
				<td align="center">
					<a href="javascript:setChkService('group_form','EDITSERVICE','EditorsDesk',reqA)">
						<img src="/actrellis/defaultskin/images/ico_edit.gif" border="0">
					</a>
				</td>
			</tr>

*/

}