/* Generated by Together */

package org.yang.web.view.controls.jsStyle;

import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.WebControl;

public class TextButtonElement extends Button
{
   private String text = "Upload";
   public void setText(String text) { this.text = text; }

   public void render(JspWriter writer) throws Exception
   {
      writer.println("<input type=\"submit\" value=\""+text+"\">");
   }
}