/* Generated by Together */
package org.yang.customized.gtf.services.tglScheduler.web;
import org.yang.web.view.controls.WebControlBuilder;
import org.yang.web.view.controls.WebControl;
import org.yang.web.controller.GenericBean;
import org.yang.web.view.controls.jsStyle.panel.Panel;
import org.yang.web.view.controls.jsStyle.panel.GenericPanel;
import org.yang.web.view.controls.jsStyle.panel.TabPanelElement;
import org.yang.web.view.controls.jsStyle.ButtonElement;
import org.yang.web.view.controls.jsStyle.SelectElement;
import org.yang.web.view.controls.jsStyle.calendar.WebCalendar;

public class CalendarBuilder implements WebControlBuilder
{
   String codeBase = null;

   public WebControl build(GenericBean bean) throws Exception
   {
      CalendarBean panelBean = (CalendarBean)bean;
      codeBase = panelBean.getAppBase() + panelBean.getGuiBase();

      WebCalendar calendar = null;
      if(null==(calendar=(WebCalendar)panelBean.getControl("calendar")))
      {
         calendar = createCalendar(panelBean);
         panelBean.setControl("calendar", calendar);
      }
      calendar.setDisplayedYear(panelBean.getDisplayedYear());
      calendar.setDisplayedMonth(panelBean.getDisplayedMonth());
      calendar.setDisplayedDay(panelBean.getDisplayedDay());

      return calendar;
   }

   private WebCalendar createCalendar(CalendarBean accountBean)
   {
      WebCalendar calendar = WebCalendar.create(WebCalendar.GTF, accountBean.getCalendarView());
      calendar.setCodeBase(codeBase);
      calendar.setSwitchViewLink("#");
      calendar.setSwitchTimeActionLink("/wf/calendar1.wf?actiontype=switchTime");
      calendar.setBackwardActionLink("/wf/calendar1.wf?actiontype=backward");
      calendar.setForwardActionLink("/wf/calendar1.wf?actiontype=forward");

      return calendar;
   }
}