/* Generated by Together */

package org.yang.customized.gtf.services.tglScheduler.web;
import javax.servlet.jsp.PageContext;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.WebControl;
import java.util.ArrayList;

public class DayTask extends WebControl
{
   private String project = null;
   public void setProject(String project) { this.project = project; }

   private String expDate = null;
   public void setExpDate(String expDate) { this.expDate = expDate; }

   private String xferDate = null;
   public void setXferDate(String xferDate) { this.xferDate = xferDate; }

   private String strain = null;
   public void setStrain(String strain) { this.strain = strain; }

   private String quantity = null;
   public void setQuantity(String quantity) { this.quantity = quantity; }

   //private String order = null;
   //public void setOrder(String order) { this.order = order; }

   private String pms = null;
   public void setPms(String pms) { this.pms = pms; }

   private String hcgMate = null;
   public void setHcgMate(String hcgMate) { this.hcgMate = hcgMate; }

   private String plugDate = null;
   public void setPlugDate(String plugDate) { this.plugDate = plugDate; }

   public DayTask() {}

   public void render(JspWriter writer) throws Exception
   {
      writer.println("                  <tr bgcolor='#ffffff'>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+project+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+strain+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+quantity+"</font></td>");
      //writer.println("                    <td nowrap align='center' class='smaller' width='60' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+order+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+pms+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+hcgMate+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+plugDate+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+expDate+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+xferDate+"</font></td>");
      writer.println("                  </tr>");
   }
}
