/* Generated by Together */
package org.yang.web.view.controls.jsStyle.dataSheet;

import org.yang.web.view.controls.WebControl;
import javax.servlet.jsp.JspWriter;

/**
 * @testcase org.test.org.yang.web.view.controls.jsStyle.TestListItem 
 */
public abstract class DataItem extends WebControl implements Comparable
{
   protected String id = null;
   public void setId(String id) { this.id = id; }
   public String getId() { return id; }

   protected String name = null;
   public void setName(String name) { this.name = name; }
   public String getName() { return name; }

   protected boolean isReadOnly = true;
   public void setIsReadOnly(boolean isReadOnly) { this.isReadOnly = isReadOnly; }
   public boolean getIsReadOnly() { return isReadOnly; }

   private String width = null;
   public String getWidth() { return width; }
   public void setWidth(String width) { this.width = width; }

   protected boolean isSortable = true;
   public void setIsSortable(boolean isSortable) { this.isSortable = isSortable; }
   public boolean getIsSortable() { return isSortable; }

   protected String titleLink = null;
   public void setTitleLink(String titleLink) { this.titleLink = titleLink; }
   public String getTitleLink() { return titleLink; }

   protected String actionLink = null;
   public void setActionLink(String actionLink) { this.actionLink = actionLink; }
   public String getActionLink() { return actionLink; }

   protected String actionTarget = null;
   public void setActionTarget(String actionTarget) { this.actionTarget = actionTarget; }
   public String getActionTarget() { return actionTarget; }

   protected String bgcolor = null;
   public void setBgcolor(String bgcolor) { this.bgcolor = bgcolor; }
   public String getBgcolor() { return bgcolor; }

   protected String dataNAText = "N/A";
   public void setDataNAText(String dataNAText) { this.dataNAText = dataNAText; }
   public String getDateNAText() { return dataNAText; }

   protected boolean isHighlight = false;
   public void setIsHighlight(boolean isHighlight) { this.isHighlight = isHighlight; }

   protected String highlightColor = "#FFFF00";
   public void setHighlightColor(String highlightColor) { this.highlightColor = highlightColor; }

   public DataItem()
   {
      super();
   }

   public int compareTo(Object object)
   {
      return 0;
   }
}