/* Generated by Together */

package org.yang.customized.gtf.services.domainManager;

import org.yang.services.domainMgr.Domain;
import org.yang.services.dataAccess.genericDAO.Storable;

public class GTFDomain extends Domain
{
   static final long serialVersionUID = 4711296382979765999L;

   public static int CREATE = 0;
   public static int UPDATE = 1;

   private int action = CREATE;
   public void setAction(int action) { this.action = action; }
   public int getAction() { return action; }

   private String key_id = "";
   public String getId(){ return key_id; }
   public void setId(String key_id){ this.key_id = key_id; }

   private String col_accountId ="";
   public void setAccountId(String accountId) { this.col_accountId = accountId; }
   public String getAccountId() { return col_accountId; }

   private String col_protocolNumber = "";
   public void setProtocolNumber(String protocolNumber) { this.col_protocolNumber = protocolNumber; }
   public String getProtocolNumber() { return col_protocolNumber; }

   private String col_description = "";
   public String getDescription(){ return col_description; }
   public void setDescription(String description){ this.col_description = description; }

   public GTFDomain() 
   {
      super();	
   }
   
   public String prepareSQLCreateTable()
   {
      StringBuffer sql =
           new StringBuffer("CREATE TABLE ").append(this.getTablename())
                                            .append(" (id varchar(64) not null")
                                            .append(", accountId(255)")
                                            .append(", protocolNumber varchar(255)")
                                            .append(", description varchar(255)")
                                            .append(", primary key(id))");
      return sql.toString();
   }

   public Storable create()
   {
      return new GTFDomain();
   }

   public String[] displayColumns()
   {
      return new String[]{"accountId", "protocolNumber", "description"};
   }

   public String[] displayColumnNames()
   {
      return new String[]{"Account ID", "Protocol number", "Description"};
   }

   public String[] displayControlElements()
   {
      return new String[]{"text field", "text field", "text area"};
   }
}
