/* Generated by Together */

package org.yang.services.accountmgr.SimpleDAOs;
import java.util.Hashtable;
import java.util.Properties;
import org.yang.services.dbService.RDBMS;
import org.yang.services.dbService.RDBMSFactory;
import org.yang.services.accountmgr.DAOFactory;
import org.yang.services.accountmgr.UserDAO;
import org.yang.services.accountmgr.GroupDAO;
import org.yang.services.accountmgr.PermissionDAO;

/**
 * @testcase org.test.org.yang.services.accountmgr.SimpleDAOs.TestSimpleDAOFactoryImpl 
 */
public class SimpleDAOFactoryImpl extends DAOFactory
{
   RDBMS rdbms = RDBMSFactory.getInstance().getSystemRDBMS();

   private String domain = null;

   public SimpleDAOFactoryImpl(){}
   
   public SimpleDAOFactoryImpl(String domain)
   {  
     this.domain = domain;
   }

   public UserDAO getUserDAO()
   {
      return new SimpleUserDAOImpl(domain, rdbms);
   }

   public GroupDAO getGroupDAO()
   {
      return new SimpleGroupDAOImpl(domain, rdbms);
   }

   public PermissionDAO getPermissionDAO()
   {
      return new SimplePermissionDAOImpl(domain, rdbms);
   }
}