/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.WebControl;

public class HiddenField extends WebControl
{
   private String name = null;
   public void setName(String name) { this.name = name; }

   private String value = null;
   public void setValue(String value) { this.value = value; }

   public void render(JspWriter writer) throws Exception
   {
      writer.print("    <input type  = \"hidden\"");
      writer.print("           name  = \"" + name + "\"");
      writer.print("           value = \"" + value + "\">");
   }
}
