/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.JspWriter;

public class RadioButtonGroup extends FormElement 
{
   private String name = null;
   public void setName(String name) { this.name = name; }
   public String getName() { return name; }

   private String[] values = null;
   public void setValues(String[] values) { this.values = values; }

   private String unit = null;
   public void setUnit(String unit) { this.unit = unit; }

   private String[] displayNames = null;
   public void setDisplayNames(String[] displayNames) { this.displayNames = displayNames; }

   private String selectedValue = null;
   public void setSelectedValue(String selectedValue) { this.selectedValue = selectedValue; }
   public String getSelectedValue() { return selectedValue; }

   public void printBody(JspWriter writer) throws Exception
   {
      if(null==displayNames)
         displayNames = values;

      for(int i=0; i<values.length; i++)
      {
         writer.print( "<input id=\"" + id + "\" ");
         writer.print( "       onclick=\"" + onChange + "\" ");
         if(null!=selectedValue&&selectedValue.equals(values[i]))
         {
            writer.print( "       type=\"radio\" name=\"" + name + "\" value=\"" + values[i] + "\" checked  >" + displayNames[i] + "</input>");
         }
         else
         {
            writer.print( "       type=\"radio\" name=\"" + name + "\" value=\"" + values[i] + "\" >" + displayNames[i] + "</input>");
         }

         if(!isVertical)
            writer.print("&#32;");
         else
            writer.print("<br>");
      }
   }
}
