/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.JspWriter;

public class TextAreaElement extends FormElement 
{
   private String name = null;
   public void setName(String name) { this.name = name; }

   private String value = null;
   public void setValue(String value) { this.value = value; }

   private String rows = "3";
   public void setRows(String rows) { this.rows = rows; }

   private String cols = "30";
   public void setCols(String cols) { this.cols = cols; }

   protected void printBody(JspWriter writer) throws Exception
   {
      writer.print("    <textarea id   = \"" + id + "\"");
      writer.print("              name = \"" + name + "\"");
      writer.print("              rows = \"" + rows + "\"");
      writer.print("              wrap = \"SOFT\"");
      writer.print("              cols = \"" + cols + "\"");
      writer.print("              onChange = \"" + onChange + "\"");
      if(isReadOnly)
         writer.print("           READONLY");
      writer.print("    >" + value + "</textarea>");
   }
}
