/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.PageContext;
import javax.servlet.jsp.JspWriter;
import javax.servlet.http.HttpSession;
import org.yang.web.applicationContainer.SelectorItem;
import java.util.Arrays;

public class UISelector extends GenericControl 
{
   protected String name = null;
   public void setName(String name) { this.name = name; }
   public String getName() { return name; }

   protected int size = 6;
   public void setSize(int size) { this.size = size; }
   public int getSize() { return size; }

   protected String unselectedBoxCaption = null;
   public void setUnselectedBoxCaption(String unselectedBoxCaption) { this.unselectedBoxCaption = unselectedBoxCaption; }
   public String getUnselectedBoxCaption() { return unselectedBoxCaption; }

   protected String addAction = null;
   public void setAddAction(String addAction) { this.addAction = addAction; }
   public String getAddAction() { return addAction; }

   protected String addIcon = null;
   public void setAddIcon(String addIcon) { this.addIcon= addIcon; }
   public String getAddIcon() { return addIcon; }   
   
   protected String addCaption = null;
   public void setAddCaption(String addCaption) { this.addCaption = addCaption; }
   public String getAddCaption() { return addCaption; }

   protected String removeAction = null;
   public void setRemoveAction(String removeAction) { this.removeAction = removeAction; }
   public String getRemoveAction() { return removeAction; }   

   protected String removeIcon = null;
   public void setRemoveIcon(String removeIcon) { this.removeIcon = removeIcon; }
   public String getRemoveIcon() { return removeIcon; }   

   protected String removeCaption = null;
   public void setRemoveCaption(String removeCaption) { this.removeCaption = removeCaption; }
   public String getRemoveCaption() { return removeCaption; }   

   protected String selectedBoxCaption = null;
   public void setSelectedBoxCaption(String selectedBoxCaption) { this.selectedBoxCaption = selectedBoxCaption; }
   public String getSelectedBoxCaption() { return selectedBoxCaption; }

   protected SelectorItem[] selectedItems = null;
   public void setSelectedItems(SelectorItem[] selectedItems) { this.selectedItems = selectedItems; }

   protected SelectorItem[] unselectedItems = null;
   public void setUnselectedItems(SelectorItem[] unselectedItems) { this.unselectedItems = unselectedItems; }

   protected boolean isReadOnly = false;
   public void setIsReadOnly(boolean isReadOnly) { this.isReadOnly = isReadOnly; }

   protected void printBody(JspWriter writer) throws Exception
   {
      String pt1   = "        <tr>\n" +
                    "          <td>\n" +
                    "            <table border      = \"1\"\n" +
                    "                   cellspacing = \"0\"\n" +
                    "                   cellpadding = \"3\"\n" +
                    "                   bordercolorlight = \"#CCCCCC\"\n" +
                    "                   bordercolor      = \"#CCCCCC\"\n" +
                    "                   bordercolordark  = \"#FFFFFF\"\n" +
                    "                   bgcolor          = \"#EAEAEA\"\n" +
                    "                   align            = \"center\"\n" +
                    "                   width            = \"100%\"\n" +
                    "                   ID               = \"Table7\">\n" +
                    "              <tr align=\"center\">\n" +
                    "                <td nowrap>\n" +
                    "                  <table width=\"200\" border=\"0\" cellspacing=\"0\" cellpadding=\"3\" ID=\"Table8\">\n" +
                    "                    <tr bgcolor=\"#CCCCCC\" align=\"center\">\n" +
                    "                      <td nowrap class=\"bigger\"><b>" + unselectedBoxCaption + "</b></td>\n" +
                    "                    </tr>\n" +
                    "                    <tr align=\"center\">\n" +
                    "                      <td>\n" +
                    "                        <select name=\"selected" + name + "\" size=\""+size+"\" multiple ID=\"Select2\">\n";

      if(isReadOnly)
      {
         addAction = "#";
         addCaption = "Function disabled";
         removeAction = "#";
         removeCaption = "Function disabled";
      }

      String pt2 =  "                        </select>\n" +
                    "                      </td>\n" +
                    "                    </tr>\n" +
                    "                  </table>\n" +
                    "                </td>\n" +
                    "                <td nowrap valign=\"middle\">\n" +
                    "                  <p><a href=\"" + addAction + "\"><img src=\"" + addIcon + "\" border=\"0\" alt=\"" + addCaption + "\"></a></p>\n" +
                    "                  <p><a href=\"" + removeAction + "\"><img src=\"" + removeIcon + "\" border=\"0\" alt=\"" + removeCaption + "\"></p>\n" +
                    "               </td>\n" +
                    "               <td nowrap>\n" +
                    "                 <table width=\"200\" border=\"0\" cellspacing=\"0\" cellpadding=\"3\" ID=\"Table9\">\n" +
                    "                   <tr bgcolor=\"#CCCCCC\" align=\"center\">\n" +
                    "                     <td nowrap class=\"bigger\"><b>" + selectedBoxCaption + "</b></td>\n" +
                    "                   </tr>\n" +
                    "                   <tr align=\"center\">\n" +
                    "                     <td>\n" +
                    "                       <select name=\"unselected" + name + "\" size=\""+size+"\" multiple ID=\"Select3\">\n";

      String pt3 =  "                       </select>\n" +
                    "                     </td>\n" +
                    "                   </tr>\n" +
                    "                 </table>\n" +
                    "               </td>\n" +
                    "             </tr>\n" +
                    "           </table>\n" +
                    "         </td>\n" +
                    "       </tr>\n" ;

      writer.print(pt1);

      Arrays.sort(unselectedItems);
      for(int i=0; i<unselectedItems.length; i++)
      {
         writer.print("                         <option value=\"" +
                      unselectedItems[i].getId() +
                      "\">" +
                      unselectedItems[i].getValue() +
                      " </option>\n");
      }

      writer.print(pt2);

      Arrays.sort(selectedItems);
      for(int i=0; i<selectedItems.length; i++)
      {
         writer.print("                         <option value=\"" +
                      selectedItems[i].getId() +
                      "\">" +
                      selectedItems[i].getValue() +
                      " </option>\n");
      }

      writer.print(pt3);
   }
}
