/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.PageContext;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.WebControl;
import java.util.ArrayList;

public class WebAppForm extends WebControl
{
   private String id = null;
   public void setId(String id) { this.id = id; }

   private String encType = "application/x-www-form-urlencoded";
   public void setEncType(String encType) { this.encType = encType; }

   private String actionLink = null;
   public void setActionLink(String actionLink) { this.actionLink = actionLink; }

   public WebAppForm() {}

   public void render(JspWriter writer) throws Exception
   {
      if(null!=actionLink)
      {
         writer.println("<form name=\"" + id + "\" enctype=\"" + encType + "\" action=\"" + actionLink + "\" method=\"post\" id=\"" + id + "\">");
         writer.println("<input type=\"hidden\" name=\"actiontype\" value=\"\" id=\"" + id + ".hidden\">");
      }

      this.renderSubcontrols(writer);

      if(null!=actionLink)
      {
         writer.println("</form>");
      }
   }
}
