/* Generated by Together */

package org.yang.web.view.controls.jsStyle;
import javax.servlet.jsp.PageContext;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.WebControl;
import java.util.ArrayList;

public class WebControlGroup extends WebControl
{
   public WebControlGroup() {}

   public void render(JspWriter writer) throws Exception
   {
      this.renderSubcontrols(writer);
   }
}
