/* Generated by Together */

package org.yang.web.view.controls.jsStyle.navigationTree;

import javax.servlet.jsp.JspWriter;
import java.io.IOException;

public class BaseStyleImpl extends NodeStyleImpl
{
   protected String getStyle()
   {
      return "BASESTYL";
   }

   protected void printVertlineEnd(JspWriter writer) throws IOException {}
}