/* Generated by Together */
package org.yang.customized.gtf.services.reportManager.web;

import org.yang.web.view.controls.WebControl;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.jsStyle.SelectElement;
import org.yang.web.view.controls.jsStyle.CheckBoxes;
import org.yang.web.view.controls.jsStyle.CheckBoxGroup;
import java.util.Date;
import org.yang.web.view.controls.jsStyle.RadioButtonGroup;

/**
 * @testcase org.test.org.yang.web.view.controls.jsStyle.TestNavigationList 
 */
public class ReportsSearchingControl extends WebControl
{
   private String id = null;
   public void setId(String id) { this.id = id; }
   public String getId() { return id; }

   protected String actionLink = null;
   public void setActionLink(String actionLink) { this.actionLink = actionLink; }
   public String getActionLink() { return actionLink; }

   protected String codeBase = null;
   public void setCodeBase(String codeBase) { this.codeBase = codeBase; }

   private int searchYearFrom = 2003;
   public void setSearchYearFrom(int searchYearFrom){ this.searchYearFrom = searchYearFrom; }

   private int searchMonthFrom = 1;
   public void setSearchMonthFrom(int searchMonthFrom){ this.searchMonthFrom = searchMonthFrom; }

   private int searchDayFrom = 1;
   public void setSearchDayFrom(int searchDayFrom){ this.searchDayFrom = searchDayFrom; }

   private int searchYearTo = 2100;
   public void setSearchYearTo(int searchYearTo){ this.searchYearTo = searchYearTo; }

   private int searchMonthTo = 1;
   public void setSearchMonthTo(int searchMonthTo){ this.searchMonthTo = searchMonthTo; }

   private int searchDayTo = 1;
   public void setSearchDayTo(int searchDayTo){ this.searchDayTo = searchDayTo; }

   private SelectElement dateTypeSelector = null;
   public void setDateTypeSelector(SelectElement dateTypeSelector) { this.dateTypeSelector = dateTypeSelector; }

   private SelectElement searchTypeSelector = null;
   public void setSearchTypeSelector(SelectElement searchTypeSelector) { this.searchTypeSelector = searchTypeSelector; }

   private SelectElement projectTypeSelector = null;
   public void setProjectTypeSelector(SelectElement projectTypeSelector) { this.projectTypeSelector = projectTypeSelector; }

   private SelectElement labSelector = null;
   public void setLabSelector(SelectElement labSelector) { this.labSelector = labSelector; }

   private RadioButtonGroup andOr = null;
   public void setAndOr(RadioButtonGroup andOr) { this.andOr = andOr; }

   private String keywords = "";
   public void setKeywords(String keywords){ this.keywords = keywords; }

   private CheckBoxGroup displayItems = null;
   public void setDisplayItems(CheckBoxGroup displayItems) { this.displayItems = displayItems; }

   public ReportsSearchingControl()
   {
      super();
   }

   public void render(JspWriter writer) throws Exception
   {
      Date now = new Date();
      int maxYear = now.getYear()+1900;
      int maxMonth = 12;
      int maxDate = 31;

      writer.println( "    <script language=\"JavaScript\" type=\"text/javascript\">");
      writer.println( "      //---------------------------------------");
      writer.println( "      function submitForm(frm, act) {");
      writer.println( "        fm = eval('document.'+ frm);");
      writer.println( "        fm.actiontype.value = act;");
      writer.println( "        fm.submit();");
      writer.println( "      }");
      writer.println( "    </script>");
      writer.println( "      <table width=\"100%\" border=\"1\" cellspacing=\"0\" cellpadding=\"3\" bordercolorlight=\"#cccccc\" bordercolor=\"#cccccc\" bordercolordark=\"#ffffff\" bgcolor=\"#eaeaea\" align=\"center\" ID=\"Table4\">");
      writer.println( "        <form  name=\"updateData\" action=\"/wf/reportsPanel.wf\" method=\"post\" id=\"update\">");
      writer.println( "        <input type=\"hidden\" name=\"actiontype\" value=\"\" id=\"actiontype.hidden\">");
      writer.println( "        <tr>");
      writer.println( "          <td height=\"33\">");
      writer.println( "            <P>");
      writer.println( "              <font color=\"#000060\">Search by date:</font></P>");
      writer.println( "          </td>");
      writer.println( "        </tr>");
      writer.println( "        <TR>");
      writer.println( "          <TD height=\"33\">");
      writer.println( "            <P>");
      writer.println( "              <FONT color=\"#000060\">From:</FONT>");
      writer.println( "              <SELECT id=\"Select4\" name=\"searchYearFrom\" onChange=\"javascript:submitForm('updateData', 'updateData')\">");
      for(int i=2003; i<=maxYear; i++)
      {
         if(i==searchYearFrom)
            writer.println( "                <OPTION value=\"" + i + "\" selected>" + i + "</OPTION>");
         else
            writer.println( "                <OPTION value=\"" + i + "\" >" + i + "</OPTION>");
      }
      writer.println( "              </SELECT>");
      writer.println( "              <FONT color=\"#000060\">/</FONT>");
      writer.println( "              <SELECT id=\"Select5\" name=\"searchMonthFrom\" onChange=\"javascript:submitForm('updateData', 'updateData')\">");


      if(maxYear==searchYearFrom)
      {
         maxMonth = now.getMonth()+1;
         if(maxMonth==searchMonthFrom)
            maxDate = now.getDate();
      }

      for(int i=1; i<=maxMonth; i++)
      {
         if(i==searchMonthFrom)
            writer.println( "                <OPTION value=\"" + i + "\" selected>" + i + "</OPTION>");
         else
            writer.println( "                <OPTION value=\"" + i + "\" >" + i + "</OPTION>");
      }
      writer.println( "              </SELECT>");
      writer.println( "              <FONT color=\"#000060\">/</FONT>");
      writer.println( "              <SELECT id=\"Select6\" name=\"searchDayFrom\" onChange=\"javascript:submitForm('updateData', 'updateData')\">");
      for(int i=1; i<=maxDate; i++)
      {
         if(i==searchDayFrom)
            writer.println( "                <OPTION value=\"" + i + "\" selected>" + i + "</OPTION>");
         else
            writer.println( "                <OPTION value=\"" + i + "\" >" + i + "</OPTION>");
      }
      writer.println( "              </SELECT>");
      writer.println( "            </P>");
      writer.println( "          </TD>");
      writer.println( "        </TR>");
      writer.println( "        <TR>");
      writer.println( "          <TD height=\"33\">");
      writer.println( "            <P><FONT color=\"#000060\">To&nbsp;&nbsp;&nbsp; :</FONT>");
      writer.println( "              <SELECT id=\"Select1\" name=\"searchYearTo\" onChange=\"javascript:submitForm('updateData', 'updateData')\">");
      for(int i=2004; i<=maxYear; i++)
      {
         if(i==searchYearTo)
            writer.println( "                <OPTION value=\"" + i + "\" selected>" + i + "</OPTION>");
         else
            writer.println( "                <OPTION value=\"" + i + "\" >" + i + "</OPTION>");
      }
      writer.println( "              </SELECT>");
      writer.println( "              <FONT color=\"#000060\">/</FONT>");
      writer.println( "              <SELECT id=\"Select2\" name=\"searchMonthTo\" onChange=\"javascript:submitForm('updateData', 'updateData')\">");

      maxMonth = 12;
      maxDate = 31;
      if(maxYear==searchYearTo)
      {
         maxMonth = now.getMonth()+1;
         if(maxMonth==searchMonthTo)
            maxDate = now.getDate();
      }

      for(int i=1; i<=maxMonth; i++)
      {
         if(i==searchMonthTo)
            writer.println( "                <OPTION value=\"" + i + "\" selected>" + i + "</OPTION>");
         else
            writer.println( "                <OPTION value=\"" + i + "\" >" + i + "</OPTION>");
      }
      writer.println( "              </SELECT>");
      writer.println( "              <FONT color=\"#000060\">/</FONT>");
      writer.println( "              <SELECT id=\"Select3\" name=\"searchDayTo\" onChange=\"javascript:submitForm('updateData', 'updateData')\">");
      for(int i=1; i<=maxDate; i++)
      {
         if(i==searchDayTo)
            writer.println( "                <OPTION value=\"" + i + "\" selected>" + i + "</OPTION>");
         else
            writer.println( "                <OPTION value=\"" + i + "\" >" + i + "</OPTION>");
      }
      writer.println( "              </SELECT>");
      writer.println( "            </P>");
      writer.println( "          </TD>");
      writer.println( "        </TR>");

      if(null!=dateTypeSelector)
      {
         dateTypeSelector.setOnChange("javascript:submitForm('updateData', 'updateData')");
         writer.println( "        <tr>");
         writer.println( "          <td nowrap align=\"left\" class=\"smallest\" height=\"6\">");
         writer.println( "             <FONT color=\"#000060\">Date&nbsp;type&nbsp;:</FONT>");
         dateTypeSelector.printBody(writer);
         writer.println( "          </td>");
         writer.println( "        </tr>");
      }

      if(null!=projectTypeSelector)
      {
         projectTypeSelector.setOnChange("javascript:submitForm('updateData', 'updateData')");
         writer.println( "        <tr>");
         writer.println( "          <td nowrap align=\"left\" class=\"smallest\">");
         writer.println( "            <font color=\"#000060\">Project Type :</font>");
         projectTypeSelector.printBody(writer);
         writer.println( "          </td>");
         writer.println( "        </tr>");
      }

      if(null!=labSelector)
      {
         labSelector.setOnChange("javascript:submitForm('updateData', 'updateData')");
         writer.println( "        <tr>");
         writer.println( "          <td nowrap align=\"left\" class=\"smallest\" height=\"6\">");
         writer.println( "            <FONT color=\"#000060\">Lab&nbsp;Name:</FONT>");
         labSelector.printBody(writer);
         writer.println( "          </td>");
         writer.println( "        </tr>");
      }

      if(null!=searchTypeSelector)
      {
         searchTypeSelector.setOnChange("javascript:submitForm('updateData', 'updateData')");
         writer.println( "        <tr>");
         writer.println( "          <td nowrap align=\"left\" class=\"smallest\" height=\"6\">");
         writer.println( "             <FONT color=\"#000060\">Search&nbsp;by&nbsp;:</FONT>");
         searchTypeSelector.printBody(writer);
         writer.println( "          </td>");
         writer.println( "        </tr>");
      }

      if(null!=andOr)
      {
         andOr.setOnChange("javascript:submitForm('updateData', 'updateData')");
         writer.println( "        <tr>");
         writer.println( "          <td nowrap align=\"left\" class=\"smallest\" height=\"6\">");
         writer.println( "             <FONT color=\"#000060\">Logic:</FONT>");
         andOr.printBody(writer);
         writer.println( "          </td>");
         writer.println( "        </tr>");
      }

      if(null!=displayItems)
      {
         writer.println( "        <TR>");
         writer.println( "          <TD class=\"smallest\" noWrap align=\"left\">");
         displayItems.printBody(writer);
         writer.println( "          </TD>");
         writer.println( "        </TR>");
         writer.println( "        <TR>");
      }

      writer.println( "        <tr>");
      writer.println( "          <td nowrap align=\"left\" class=\"smallest\" height=\"6\">");
      writer.println( "            <font color=\"#000060\">Keywords:</font>");
      writer.println( "            <input type=\"text\" name=\"keywords\" value=\"" + keywords + "\" size=\"20\" ID=\"Text1\" onChange=\"javascript:submitForm('updateData', 'updateData')\">");
      writer.println( "          </td>");
      writer.println( "        </tr>");

      writer.println( "        </form>");

      writer.println( "        <script language=\"JavaScript\" type=\"text/javascript\">");
      writer.println( "        //---------------------------------------");
      writer.println( "        function submitFormThenTargetTo(frm, act, tar) {");
      writer.println( "          fm = eval('document.'+ frm);");
      writer.println( "          fm.actiontype.value = act;");
      writer.println( "          fm.target = tar;");
      writer.println( "          fm.submit();");
      writer.println( "        }");
      writer.println( "        </script>");
      writer.println( "        <form name=\"" + id + "\" method=\"post\" action=\"" + actionLink + "\" ID=\"" + id + "\">");
      writer.println( "        <input type=\"hidden\" name=\"actiontype\" value=\"\" >");
      writer.println( "        <input type=\"hidden\" name=\"searchYearFrom\" value=\"" + searchYearFrom + "\">");
      writer.println( "        <input type=\"hidden\" name=\"searchMonthFrom\" value=\"" + searchMonthFrom +"\">");
      writer.println( "        <input type=\"hidden\" name=\"searchDayFrom\" value=\"" + searchDayFrom +"\">");
      writer.println( "        <input type=\"hidden\" name=\"searchYearTo\" value=\"" + searchYearTo +"\">");
      writer.println( "        <input type=\"hidden\" name=\"searchMonthTo\" value=\"" + searchMonthTo +"\">");
      writer.println( "        <input type=\"hidden\" name=\"searchDayTo\" value=\"" + searchDayTo +"\">");
      writer.println( "        <input type=\"hidden\" name=\"keywords\" value=\"" + keywords +"\">");

      writer.println( "        <input type=\"hidden\" name=\"" + dateTypeSelector.getName() + "\" value=\"" + dateTypeSelector.getSelectedValue() + "\">");
      writer.println( "        <input type=\"hidden\" name=\"" + projectTypeSelector.getName() + "\" value=\"" + projectTypeSelector.getSelectedValue() + "\">");
      writer.println( "        <input type=\"hidden\" name=\"" + labSelector.getName() + "\" value=\"" + labSelector.getSelectedValue() + "\">");
      writer.println( "        <input type=\"hidden\" name=\"" + searchTypeSelector.getName() + "\" value=\"" + searchTypeSelector.getSelectedValue() + "\">");
      writer.println( "        <input type=\"hidden\" name=\"" + andOr.getName() + "\" value=\"" + andOr.getSelectedValue() + "\">");
      //String[] displayItemNames = displayItems.getValues();
      //for(int i=0; i<displayItemNames.length; i++)
      //{
      //   writer.println( "             <input type=\"hidden\" name=\"" + displayItems.getName() + "\" value=\"" + displayItemNames[i] + "\">");
      //}

      writer.println( "        <TR>");
      writer.println( "          <TD class=\"smallest\" noWrap align=\"left\">");

      this.renderSubcontrols(writer);

      writer.println( "          </TD>");
      writer.println( "        </TR>");
      writer.println( "        </form>");

      writer.println( "      </table>");
   }
}