/* Generated by Together */
package org.yang.web.services.accountManage;

import org.yang.web.view.controls.WebControlBuilder;
import org.yang.web.view.controls.WebControl;
import org.yang.web.controller.GenericBean;
import org.yang.web.view.controls.jsStyle.UIForm;
import org.yang.web.view.controls.jsStyle.TextField;
import org.yang.web.view.controls.jsStyle.PassElement;
import org.yang.web.view.controls.jsStyle.SelectElement;
import org.yang.web.view.controls.jsStyle.TextAreaElement;
import org.yang.web.view.controls.jsStyle.ButtonElement;
import org.yang.web.view.controls.jsStyle.HiddenField;
import org.yang.services.accountmgr.Group;

public class GroupInfoAccessFormBuilder implements WebControlBuilder
{
   public WebControl build(GenericBean bean) throws Exception
   {
      GroupBean groupBean = (GroupBean)bean;
      Group group = groupBean.getCurrentGroup();
      String codeBase = groupBean.getAppBase() + groupBean.getGuiBase();

      UIForm form = new UIForm();
      form.setCaption("Basic Information");

      if(!"clear".equals(groupBean.getLastActiontype()))
      {
         ButtonElement save = new ButtonElement();
         save.setAction("javascript:validateForm('group_form','updateInfo',reqA)");
         save.setName("save");
         save.setOffIcon(codeBase + "/images/English/btn_update.gif");
         save.setOnIcon(codeBase + "/images/English/btn_update_on.gif");
         save.setAlt("Update group information");
         form.addAButton(save);
      }

      ButtonElement help = new ButtonElement();
      help.setAction("javascript:top.topFrame.openSWHelpWindow('" + codeBase + "/help/English/help.jsp?right=admin_user.htm#group')");
      help.setName("help");
      help.setOffIcon(codeBase + "/images/English/btn_help.gif");
      help.setOnIcon(codeBase + "/images/English/btn_help_on.gif");
      help.setAlt("Help");
      form.addAButton(help);

      HiddenField groupId = new HiddenField();
      groupId.setName("id");
      groupId.setValue(group.getID());
      form.addASubcontrol(groupId);

      TextField groupname = new TextField();
      groupname.setTitle("Group Name");
      groupname.setName("name");
      groupname.setValue(group.getName());
      if("clear".equals(groupBean.getLastActiontype()))
         groupname.setIsReadOnly(false);
      else
         groupname.setIsReadOnly(true);
      form.addASubcontrol(groupname);

      TextAreaElement description = new TextAreaElement();
      description.setTitle("Description");
      description.setId("description");
      description.setName("description");
      description.setValue(group.getDescription());
      form.addASubcontrol(description);

      return form;
   }
}