/* Generated by Together */

package org.yang.web.controller;

public class InvocationActionException extends Exception
{
   
   /**
 *    @roseuid 3B0AAF190011
   */
   public InvocationActionException()
   {
      super();	
   }

   /**
 *    @roseuid 3B0AAF190011
   */
   public InvocationActionException(String s)
   {
      super(s);	
   }
}
