/* Generated by Together */

package org.yang.customized.gtf.services.scheduler.web;
import javax.servlet.jsp.PageContext;
import javax.servlet.jsp.JspWriter;
import org.yang.web.view.controls.WebControl;
import java.util.ArrayList;

public class DayTask extends WebControl
{
   private String project = null;
   public void setProject(String project) { this.project = project; }

   private String item = null;
   public void setItem(String item) { this.item = item; }

   private String strain = null;
   public void setStrain(String strain) { this.strain = strain; }

   private String order = null;
   public void setOrder(String order) { this.order = order; }

   private String pms = null;
   public void setPms(String pms) { this.pms = pms; }

   private String quantity = null;
   public void setQuantity(String quantity) { this.quantity = quantity; }

   private String hcgMate = null;
   public void setHcgMate(String hcgMate) { this.hcgMate = hcgMate; }

   private String plugDate = null;
   public void setPlugDate(String plugDate) { this.plugDate = plugDate; }

   private String injection = null;
   public void setInjection(String injection) { this.injection = injection; }

   public DayTask() {}

   public void render(JspWriter writer) throws Exception
   {
      writer.println("                  <tr bgcolor='#ffffff'>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+project+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+item+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='60' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+strain+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='40' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+quantity+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='60' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+order+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='60' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+pms+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='60' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+hcgMate+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='60' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+plugDate+"</font></td>");
      writer.println("                    <td nowrap align='center' class='smaller' width='60' height='25' bgcolor='#FFFFFF'><font color='#000000'>"+injection+"</font></td>");
      writer.println("                  </tr>");
   }
}
