/* Generated by Together */

package org.yang.customized.gtf.services.messageManager.web;

import org.yang.web.applicationContainer.SecuredBean;
import org.yang.customized.gtf.services.messageManager.MessageManager;
import java.util.Date;

abstract public class MessageServiceBean extends SecuredBean
{
   static final long serialVersionUID = 4711296382979769901L;

   protected transient MessageManager msgMgr = null;

   protected int calendarView = 2;
   public void setCalendarView(int calendarView){ this.calendarView = calendarView;}
   public int getCalendarView(){ return calendarView; }

   protected int displayedMonth = 0;
   public void setDisplayedMonth(int displayedMonth){ this.displayedMonth = displayedMonth; }
   public int getDisplayedMonth(){ return displayedMonth; }

   protected int displayedYear = 0;
   public void setDisplayedYear(int displayedYear){ this.displayedYear = displayedYear; }
   public int getDisplayedYear(){ return displayedYear; }

   protected int displayedDay = 0;
   public void setDisplayedDay(int displayedDay){ this.displayedDay = displayedDay; }
   public int getDisplayedDay(){ return displayedDay; }

   public MessageServiceBean()
   {
      super();
      Date now = new Date();
      displayedYear = now.getYear();
      displayedMonth = now.getMonth();
      displayedDay = now.getDate();
      System.out.println("||||||||||||||||||||||||||||||||||"+ displayedYear + ":" + displayedMonth + ":" + displayedDay);
   }

   /***************************************
    *  Implement GenericHandler's method  *
    ***************************************/

   protected void ensureResource() throws Exception
   {
      System.out.println("[MessageServiceBean::ensureResource] entering!");

      if(null==msgMgr)
         msgMgr = (MessageManager)this.passport.loadService("MessageManager");
   }

   public String whoIsIt(String domain, String user)
   {
      return passport.whoIsIt(domain, user);
   }
}